services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    command: redis-server --save 30 1 --loglevel warning